### import numpy

In [10]:
import numpy as np

In [11]:
[1,2,3]

[1, 2, 3]

In [12]:
# create an array with a specified data type
arr = np.array([1,2,3])

print(arr)
print(arr.dtype)

[1 2 3]
int32


In [13]:
np.iinfo('int64')

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

### string data type

In [14]:
# numpy string and unicode data types are fixed-length
# string_ and unicode_ will treat the longest string in the array as the default length when creating an array
arr = np.array(['4', 'acb', 'abc'], dtype=np.string_)
print(arr)
print(arr.dtype)

[b'4' b'acb' b'abc']
|S3


### create an array from a Python array

In [15]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# arr = np.array([1,2,3,4,5])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### create an array in a specified data type

In [18]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype='i2')
print(arr)

SyntaxError: invalid syntax (4080945398.py, line 2)

### create an aray of evenly spaced values within a specified interval

In [ ]:
# np.arange(start, stop, step)
arr = np.arange(0, 20,2)  
print(arr)

[ 0 15]


### create an array of evenly spaced numbers in a specified interval

In [ ]:
# np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) 
arr = np.linspace(1, 15, 10)
print(arr)

[ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]


### create an array of random values in a given shape

In [ ]:
test=np.array([[1,2,3],[4,5,6],[4,5,6]])

In [ ]:
test

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
test.shape

2

### create an array of zeros in a given shape 

In [ ]:
zeros = np.zeros((4,5), dtype='int16')
print(zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### create an array of zeros with the same shape and data type as a given array

In [ ]:
zeros = np.zeros_like(test)
print(zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### create an array of ones in a given shape 

In [ ]:
ones = np.ones((2,3), dtype = 'int8')
print(ones.dtype)

int8


### create an array of ones with the same shape and data type as a given array

In [ ]:
ones = np.ones_like(test)
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### create an array of constant values in a given shape  

In [ ]:
p = np.full((4,5,3), (1,3,2))
print(p)

[[[1 3 2]
  [1 3 2]
  [1 3 2]
  [1 3 2]
  [1 3 2]]

 [[1 3 2]
  [1 3 2]
  [1 3 2]
  [1 3 2]
  [1 3 2]]

 [[1 3 2]
  [1 3 2]
  [1 3 2]
  [1 3 2]
  [1 3 2]]

 [[1 3 2]
  [1 3 2]
  [1 3 2]
  [1 3 2]
  [1 3 2]]]


In [ ]:
p.ndim

3

### create an array of constant values with the same shape and data type as a given array

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
p = np.full_like(arr, 5)
print(p)

[5 5 5 5 5]


### create an array by repetition

In [ ]:
# repeat each element of an array by a specified number of times
# np.repeat(iterable, reps, axis=None)
arr = [1, 5, 2]
print(np.repeat(arr, 4))    # or np.repeat(range(3), 3)

[1 1 1 1 5 5 5 5 2 2 2 2]


In [ ]:
# repeat an array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [ ]:
# repeat along specified axes
print(np.tile(arr, (2,2)))

[[1 5 2 1 5 2]
 [1 5 2 1 5 2]]


### create an identity matrix with a given diagonal size

In [ ]:
identity_matrix = np.eye(2)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


In [ ]:
identity_matrix = np.identity(2)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


### create an identity matrix with a diagonal offset

In [ ]:
identity_matrix = np.eye(5, k=1)    # positive number shifts the diagonal upward
print(identity_matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
identity_matrix = np.eye(5, k=-2)   # negative number shifts the diagonal downward
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### extract the diagonal array / create a diagonal array

In [ ]:
arr = np.random.rand(5,5)
print(arr)

[[0.50576488 0.01810978 0.25745674 0.39907643 0.06669313]
 [0.82733836 0.10077079 0.25662301 0.65245824 0.34076627]
 [0.54872265 0.45483159 0.37400663 0.87726859 0.64498394]
 [0.3685771  0.82129305 0.89771416 0.51222085 0.69045859]
 [0.34245334 0.59534157 0.13079717 0.52267265 0.64270688]]


In [ ]:
type(arr) 

numpy.ndarray

In [ ]:
# extract the diagonal
print(np.diag(arr))

[0.50576488 0.10077079 0.37400663 0.51222085 0.64270688]


In [ ]:
# create a matrix with a specified diagonal array
arr = np.diag(range(1,10,2))
print(arr)

[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 5 0 0]
 [0 0 0 7 0]
 [0 0 0 0 9]]


# 2. Inspect Arrays

In [ ]:
arr = np.array([[1,5,3,4], [4,5,6,7],[4,7,6,8]], dtype=np.int32)

### inspect general information of an array

In [ ]:
arr

array([[1, 5, 3, 4],
       [4, 5, 6, 7],
       [4, 7, 6, 8]])

In [ ]:
print(np.info(arr))

class:  ndarray
shape:  (3, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x15117a21dc0
byteorder:  little
byteswap:  False
type: int32
None


### inspect the data type of an array

In [ ]:
print(arr.dtype)

int32


In [ ]:
arr

array([[1, 5, 3, 4],
       [4, 5, 6, 7],
       [4, 7, 6, 8]])

### inspect the dimension of an array

In [ ]:
print(arr.shape)

(3, 4)


In [ ]:
arr = np.array([[1,5,3,4], [4,5,6,7],[4,7,6,8],[9,10,11,12]], dtype=np.int32)

### inspect length of an array

In [ ]:
print(arr.size)

16


### inspect the number of dimensions of an array

In [ ]:
print(arr.ndim)

2


### inspect the number of elements in an array

In [ ]:
print(arr.itemsize)
print(len(arr))

4
4


### inspect the memory size of an array (in byte)

In [ ]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

72


# 3. Sampling Methods

### set seed

In [ ]:
np.random.seed(123)
np.random.rand(3,3)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ]])

### generate a random sample from interval [0, 1) in a given shape

In [ ]:
# generate a random scalar
print(np.random.rand())      

0.24989901388011448


In [ ]:
# generate a 1-D array
print(np.random.rand(3))           

[0.9176299  0.26414685 0.71777369]


In [ ]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.86571503 0.80707948 0.21055058]
 [0.16724303 0.04670639 0.03942231]
 [0.20023081 0.9985434  0.37278698]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [ ]:
np.mean(np.random.randn(10000000,3))

-0.00010418624186355136

### generate an array of random integers in a given interval [low, high)

In [ ]:
# np.ranodm.randint(low, high, size, dtype)
np.random.seed(123)
print(np.random.randint(1, 100, (4,5,5)))

[[[67 93 99 18 84]
  [58 87 98 97 48]
  [74 33 47 97 26]
  [84 79 37 97 81]
  [69 50 56 68  3]]

 [[85 40 67 85 48]
  [62 49  8 93 53]
  [98 86 95 28 35]
  [98 77 41  4 70]
  [65 76 35 59 11]]

 [[23 78 19 16 28]
  [31 53 71 27 81]
  [ 7 15 76 55 72]
  [ 2 44 59 56 26]
  [51 85 57 50 13]]

 [[19 82  2 52 45]
  [49 57 92 50 87]
  [ 4 68 12 22 90]
  [99  4 12  4 95]
  [ 7 10 88 15 84]]]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [ ]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(2))
print(np.random.random(2))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.34345601 0.51312815]
[0.66662455 0.10590849]
[0.13089495 0.32198061 0.66156434 0.84650623 0.55325734 0.85445249
 0.38483781 0.3167879  0.35426468 0.17108183]
[0.82911263 0.33867085 0.55237008 0.57855147 0.52153306 0.00268806
 0.98834542 0.90534158 0.20763586 0.29248941]


### shuffle an array in place

In [ ]:
arr = np.array(range(10))
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.random.shuffle(arr)
print(arr)

[8 9 1 3 6 5 0 7 4 2]


In [ ]:
arr

array([8, 9, 1, 3, 6, 5, 0, 7, 4, 2])

# 4. Math Functions

In [ ]:
arr = np.random.randint(1,10,(5,5))

In [ ]:
arr

array([[3, 5, 9, 2, 3],
       [2, 2, 4, 6, 1],
       [9, 2, 7, 4, 4],
       [6, 8, 3, 4, 4],
       [4, 9, 7, 8, 7]])

### element-wise addition, subtraction, multiplication and division

In [ ]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[13 15 19 12 13]
 [12 12 14 16 11]
 [19 12 17 14 14]
 [16 18 13 14 14]
 [14 19 17 18 17]]
[[-7 -5 -1 -8 -7]
 [-8 -8 -6 -4 -9]
 [-1 -8 -3 -6 -6]
 [-4 -2 -7 -6 -6]
 [-6 -1 -3 -2 -3]]
[[30 50 90 20 30]
 [20 20 40 60 10]
 [90 20 70 40 40]
 [60 80 30 40 40]
 [40 90 70 80 70]]
[[0.3 0.5 0.9 0.2 0.3]
 [0.2 0.2 0.4 0.6 0.1]
 [0.9 0.2 0.7 0.4 0.4]
 [0.6 0.8 0.3 0.4 0.4]
 [0.4 0.9 0.7 0.8 0.7]]


In [ ]:
arr1 = np.array([1,2,3])
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memoryarr = np.array([1,2,3])
arr0=np.add(arr1, [8,9,10])
print(arr0)

arr2=np.subtract(arr1, [8,9,10])
print(arr2)

arr3=np.multiply(arr1, [1,2,3])
print(arr3)
arr4=np.divide(arr1,[4,2,3])
print(arr4)

[ 9 11 13]
[-7 -7 -7]
[1 4 9]
[0.25 1.   1.  ]


### element-wise exponentiation

In [ ]:
a=np.exp(arr1) # e = 2.71828183
print(a)

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
arr1

array([1, 2, 3])

### element-wise logorithm

In [ ]:
# natural log
print(np.log(a))      

[1. 2. 3.]


In [ ]:
# base 2
print(np.log2(arr))     

[[1.5849625  2.32192809 3.169925   1.         1.5849625 ]
 [1.         1.         2.         2.5849625  0.        ]
 [3.169925   1.         2.80735492 2.         2.        ]
 [2.5849625  3.         1.5849625  2.         2.        ]
 [2.         3.169925   2.80735492 3.         2.80735492]]


In [ ]:
# base 10
print(np.log10(arr))    

[[0.47712125 0.69897    0.95424251 0.30103    0.47712125]
 [0.30103    0.30103    0.60205999 0.77815125 0.        ]
 [0.95424251 0.30103    0.84509804 0.60205999 0.60205999]
 [0.77815125 0.90308999 0.47712125 0.60205999 0.60205999]
 [0.60205999 0.95424251 0.84509804 0.90308999 0.84509804]]


In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]
 [4 7 6]]


### element-wise square root

In [ ]:
print(np.sqrt(arr))

[[1.73205081 2.23606798 3.         1.41421356 1.73205081]
 [1.41421356 1.41421356 2.         2.44948974 1.        ]
 [3.         1.41421356 2.64575131 2.         2.        ]
 [2.44948974 2.82842712 1.73205081 2.         2.        ]
 [2.         3.         2.64575131 2.82842712 2.64575131]]


### element-wise sine and cosine

In [ ]:
print(np.sin(arr))

[[ 0.14112001 -0.95892427  0.41211849  0.90929743  0.14112001]
 [ 0.90929743  0.90929743 -0.7568025  -0.2794155   0.84147098]
 [ 0.41211849  0.90929743  0.6569866  -0.7568025  -0.7568025 ]
 [-0.2794155   0.98935825  0.14112001 -0.7568025  -0.7568025 ]
 [-0.7568025   0.41211849  0.6569866   0.98935825  0.6569866 ]]


In [ ]:
print(np.cos(arr))

[[-0.9899925   0.28366219 -0.91113026 -0.41614684 -0.9899925 ]
 [-0.41614684 -0.41614684 -0.65364362  0.96017029  0.54030231]
 [-0.91113026 -0.41614684  0.75390225 -0.65364362 -0.65364362]
 [ 0.96017029 -0.14550003 -0.9899925  -0.65364362 -0.65364362]
 [-0.65364362 -0.91113026  0.75390225 -0.14550003  0.75390225]]


### compute the min and max along a specified axis

In [ ]:
arr = np.random.randint(1,100,(3,4))
arr

array([[36, 30,  2, 84],
       [69, 31,  8, 94],
       [61, 66, 77, 68]])

In [ ]:
# calculate min along the row
print(np.min(arr, axis = 0))

[36 30  2 68]


In [ ]:
# calculate max along the column
print(np.max(arr, axis=1))    

[84 94 77]


In [ ]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

94
2


### compute element-wise min and max of two arrays

In [ ]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


In [ ]:
print(np.maximum(arr2, arr1))

[1 4 5 8 9]


In [ ]:
print(np.minimum(arr1, arr2))

[0 3 3 7 7]


### compute the mean

In [ ]:
arr[:][0]

array([0.17405168, 0.07610341, 0.07247139, 0.38280365, 0.14892688])

In [ ]:
arr[0].mean()

0.17087140437035092

In [ ]:
aa=np.array(range(24)).reshape(4,6)

In [ ]:
print(aa)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
np.mean(aa,axis=1)

array([ 2.5,  8.5, 14.5, 20.5])

In [ ]:
# compute the overall mean
print(np.mean(arr))

7.5


In [ ]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[6. 7. 8. 9.]


In [ ]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[ 1.5  5.5  9.5 13.5]


### compute the median

In [ ]:
# compute the overall median
print(np.median(arr))

7.5


In [ ]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[6. 7. 8. 9.]


In [ ]:
# compute the median along the column
print(np.median(arr, axis=1))

[ 1.5  5.5  9.5 13.5]


### compute the standard deviation & variance

In [ ]:
# compute the overall standard deviation
print(np.std(arr))

0.2936361710935977


In [ ]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.32685874 0.24746738 0.30753265 0.26847058 0.23152403]


In [ ]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.11319937 0.3393323  0.19671493 0.14862537 0.27397649]


In [ ]:
# compute the overall variance
print(np.var(arr))

0.08622220097450857


In [ ]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.10683664 0.0612401  0.09457633 0.07207645 0.05360338]


In [ ]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.0128141  0.11514641 0.03869676 0.0220895  0.07506312]


### compute the covariance & correlation

In [ ]:
arr = np.random.rand(5,8)

In [ ]:
print(np.cov(arr))

[[ 0.04210005  0.01296167 -0.03405659  0.01403708 -0.00110985]
 [ 0.01296167  0.13681661  0.04243258 -0.00934193  0.0030432 ]
 [-0.03405659  0.04243258  0.06954622 -0.02142347  0.00782999]
 [ 0.01403708 -0.00934193 -0.02142347  0.06927115  0.02600007]
 [-0.00110985  0.0030432   0.00782999  0.02600007  0.04054453]]


In [ ]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.99588696]
 [-0.99588696  1.        ]]


### compute cumulative sum & product

In [ ]:
arr

array([[0.86899972, 0.78747141, 0.38478237, 0.80083789, 0.9065035 ,
        0.93253643, 0.46552536, 0.8177257 ],
       [0.89925492, 0.94917973, 0.32297717, 0.13643311, 0.61970842,
        0.93133274, 0.81749976, 0.05435915],
       [0.51732542, 0.68699858, 0.80485377, 0.15679071, 0.52802804,
        0.2225223 , 0.65722151, 0.11181467],
       [0.96090226, 0.38978381, 0.4211296 , 0.32667663, 0.31275587,
        0.47357096, 0.38741185, 0.92482584],
       [0.93109313, 0.24001444, 0.58460236, 0.46996818, 0.6434775 ,
        0.39935424, 0.57766264, 0.49399704]])

In [ ]:
# 0 1, 2, 3, 4 - 1 2 3 4 - 3 3 4 - 6 4 - 10 

In [ ]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[0.86899972 0.78747141 0.38478237 0.80083789 0.9065035  0.93253643
  0.46552536 0.8177257 ]
 [1.76825464 1.73665115 0.70775954 0.937271   1.52621192 1.86386917
  1.28302512 0.87208485]
 [2.28558006 2.42364973 1.5126133  1.0940617  2.05423995 2.08639147
  1.94024663 0.98389952]
 [3.24648232 2.81343353 1.9337429  1.42073833 2.36699583 2.55996243
  2.32765848 1.90872536]
 [4.17757545 3.05344797 2.51834526 1.8907065  3.01047333 2.95931666
  2.90532111 2.4027224 ]]


In [ ]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.86899972 1.65647114 2.04125351 2.8420914  3.7485949  4.68113132
  5.14665669 5.96438239]
 [0.89925492 1.84843465 2.17141182 2.30784493 2.92755334 3.85888609
  4.67638584 4.73074499]
 [0.51732542 1.204324   2.00917777 2.16596847 2.69399651 2.91651881
  3.57374033 3.68555499]
 [0.96090226 1.35068606 1.77181566 2.09849229 2.41124816 2.88481912
  3.27223096 4.1970568 ]
 [0.93109313 1.17110757 1.75570993 2.2256781  2.8691556  3.26850984
  3.84617248 4.34016952]]


In [ ]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[0.86899972 0.78747141 0.38478237 0.80083789 0.9065035  0.93253643
  0.46552536 0.8177257 ]
 [0.78145228 0.74745191 0.12427592 0.1092608  0.56176785 0.86850171
  0.38056687 0.04445088]
 [0.40426513 0.5134984  0.10002394 0.01713108 0.29662917 0.193261
  0.25011673 0.00497026]
 [0.38845927 0.20015336 0.04212304 0.00559632 0.09277252 0.0915228
  0.09689819 0.00459662]
 [0.36169176 0.0480397  0.02462523 0.00263009 0.05969703 0.03655002
  0.05597446 0.00227072]]


In [ ]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[8.68999724e-01 6.84312442e-01 2.63311364e-01 2.10869716e-01
  1.91154136e-01 1.78258195e-01 8.29837107e-02 6.78579130e-02]
 [8.99254917e-01 8.53554542e-01 2.75678627e-01 3.76116927e-02
  2.33082825e-02 2.17077666e-02 1.77460939e-02 9.64662623e-04]
 [5.17325421e-01 3.55401830e-01 2.86046501e-01 4.48494330e-02
  2.36817580e-02 5.26971933e-03 3.46337291e-03 3.87255883e-04]
 [9.60902255e-01 3.74544138e-01 1.57731623e-01 5.15272345e-02
  1.61154451e-02 7.63180679e-03 2.95665235e-03 2.73438849e-03]
 [9.31093131e-01 2.23475794e-01 1.30644476e-01 6.13987461e-02
  3.95087117e-02 1.57779714e-02 9.11434455e-03 4.50245923e-03]]


### element-wise comparison

In [ ]:
arr1 = np.array([1,2,3,4,5,1])
arr2 = np.array([5,4,3,2,1,6])

In [ ]:
arr1[arr2<arr1]

array([4, 5])

# 5. Slicing & Indexing

In [ ]:
arr = np.array(range(100)).reshape((10,10))

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### select an element by row and column indices

In [ ]:
print(arr[4][5])
# or more concisely
print(arr[4,5])

45
45


### indexing with slicing

In [ ]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


### assign a scalar to a slice by broadcasting

In [ ]:
arr[6:8,:] = 99    # or simply arr[1:3]
arr[3:7,0:4] = 100
print(arr)

[[ 88  88  88  88   4   5   6   7   8   9]
 [ 88  88  88  88  14  15  16  17  18  19]
 [ 88  88  88  88  24  25  26  27  28  29]
 [100 100 100 100  34  35  36  37  38  39]
 [100 100 100 100  44  45  46  47  48  49]
 [100 100 100 100  54  55  56  57  58  59]
 [100 100 100 100  99  99  99  99  99  99]
 [ 88  88  88  88  99  99  99  99  99  99]
 [ 88  88  88  88  84  85  86  87  88  89]
 [ 88  88  88  88  94  95  96  97  98  99]]


### boolean indexing

In [26]:
arr1 = np.arange(25).reshape((5,5))
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr3=np.array([1,2,3,4,5])

In [22]:
arr3

array([1, 2, 3, 4, 5])

In [23]:
arr3[arr3>1]

array([2, 3, 4, 5])

In [ ]:
bools = np.array([True, False, False, True, False])

In [24]:
arr3

array([1, 2, 3, 4, 5])

In [ ]:
bools

array([ True, False, False,  True, False])

In [25]:
arr3[bools]

array([1, 4])

In [27]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
print(arr1[bools])

[ 1 17]


In [ ]:
bools

array([ True, False, False,  True, False])

In [28]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
# negate the condition
print(arr1[bools, bools])    

[ 0 18]


In [37]:
arr2 = np.array([1,2,3,4,5])

In [ ]:
(arr2 < 2) | (arr2>4) # | - or,  & - and

array([ True, False, False, False,  True])

In [40]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
# multiple conditions
print(arr1[(arr1<2) | (arr1>4)])    

[ 0  1  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


### find elements/indices by conditions

In [ ]:
arr = np.arange(16).reshape(4,4)

In [ ]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [ ]:
arr>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, 5, 'd'))

[['d' 'd' 'd' 'd']
 ['d' 'd' '5' '5']
 ['5' '5' '5' '5']
 ['5' '5' '5' '5']]


# 6. Sort an Array

In [48]:
arr = np.random.randint(1,5, (5,5))

In [49]:
arr

array([[3, 1, 3, 2, 3],
       [3, 4, 3, 4, 1],
       [3, 3, 1, 2, 4],
       [3, 1, 2, 2, 3],
       [1, 1, 1, 1, 1]])

In [ ]:
print(arr)

[[1 4 4 3 1]
 [3 2 1 1 4]
 [1 1 4 1 1]
 [2 1 1 1 3]
 [4 3 2 2 1]]


### sort an array along a specified axis

In [ ]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))  

[[1 1 1 1 1]
 [1 1 1 1 1]
 [2 2 2 1 1]
 [3 3 4 2 3]
 [4 4 4 3 4]]


In [ ]:
arr

array([[1, 4, 4, 3, 1],
       [3, 2, 1, 1, 4],
       [1, 1, 4, 1, 1],
       [2, 1, 1, 1, 3],
       [4, 3, 2, 2, 1]])

In [ ]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [2 2 2 1 1]
 [3 3 4 2 3]
 [4 4 4 3 4]]


In [ ]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 2 2 2]
 [2 3 3 3 4]
 [3 4 4 4 4]]


In [ ]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 2 2 2]
 [2 3 3 3 4]
 [3 4 4 4 4]]


# 7. Manipulate an Array

### transpose an array

In [ ]:
arr=np.random.rand(24)

In [ ]:
arr

array([0.42157384, 0.23173399, 0.00239694, 0.11711431, 0.92736355,
       0.75890033, 0.60129952, 0.76822979, 0.46100745, 0.35563435,
       0.20469865, 0.91100742, 0.05544488, 0.02454634, 0.37711547,
       0.08360954, 0.84103044, 0.29887963, 0.46810377, 0.76176182,
       0.47835739, 0.22341177, 0.5085165 , 0.3127548 ])

In [ ]:
arr1=np.arange(120).reshape(24,5)

In [ ]:
arr

array([0.42157384, 0.23173399, 0.00239694, 0.11711431, 0.92736355,
       0.75890033, 0.60129952, 0.76822979, 0.46100745, 0.35563435,
       0.20469865, 0.91100742, 0.05544488, 0.02454634, 0.37711547,
       0.08360954, 0.84103044, 0.29887963, 0.46810377, 0.76176182,
       0.47835739, 0.22341177, 0.5085165 , 0.3127548 ])

In [62]:
import pandas as pd
temp=pd.DataFrame(arr1).rename(columns={0:'Age',1:'Salary',2:'Exp',3:'ten',4:'fam_siz'})
pd.read_csv
temp.to_csv("result.csv")

In [ ]:
np.array(arr1).shape

(24, 5)

In [ ]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[0.42157384 0.23173399 0.00239694 0.11711431 0.92736355 0.75890033
 0.60129952 0.76822979 0.46100745 0.35563435 0.20469865 0.91100742
 0.05544488 0.02454634 0.37711547 0.08360954 0.84103044 0.29887963
 0.46810377 0.76176182 0.47835739 0.22341177 0.5085165  0.3127548 ]
[0.42157384 0.23173399 0.00239694 0.11711431 0.92736355 0.75890033
 0.60129952 0.76822979 0.46100745 0.35563435 0.20469865 0.91100742
 0.05544488 0.02454634 0.37711547 0.08360954 0.84103044 0.29887963
 0.46810377 0.76176182 0.47835739 0.22341177 0.5085165  0.3127548 ]
[0.42157384 0.23173399 0.00239694 0.11711431 0.92736355 0.75890033
 0.60129952 0.76822979 0.46100745 0.35563435 0.20469865 0.91100742
 0.05544488 0.02454634 0.37711547 0.08360954 0.84103044 0.29887963
 0.46810377 0.76176182 0.47835739 0.22341177 0.5085165  0.3127548 ]


### append elements to an array

In [ ]:
arr = np.array([1,2,3])

In [ ]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [ ]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [ ]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [ ]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 2, [1,2,3])    
print(arr3)

[1 2 1 2 3 3]


### delete elements from an array

In [ ]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [ ]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

In [ ]:
arr = np.array([1,2,3])

In [ ]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

# 8. Combine & Split an Array

In [ ]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [ ]:
arr1.shape

(2, 4)

In [ ]:
arr2.shape

(2, 4)

### ```np.concatenate((a, b), axis=0)```

In [ ]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [ ]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [ ]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [ ]:
arr = np.random.rand(4,4)

In [ ]:
arr

array([[8.74706367e-01, 8.23387037e-01, 8.81133879e-01, 3.39651185e-01],
       [3.26079250e-02, 6.38509718e-01, 1.35416937e-01, 4.63886318e-01],
       [8.91338608e-01, 6.96138415e-04, 5.25016035e-01, 9.95740514e-01],
       [8.48931654e-01, 5.66249045e-01, 6.20470154e-01, 7.34694386e-01]])

In [ ]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1[0])  

[[0.87470637 0.82338704 0.88113388 0.33965119]
 [0.03260793 0.63850972 0.13541694 0.46388632]]


In [ ]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[8.74706367e-01, 8.23387037e-01],
       [3.26079250e-02, 6.38509718e-01],
       [8.91338608e-01, 6.96138415e-04],
       [8.48931654e-01, 5.66249045e-01]]), array([[0.88113388, 0.33965119],
       [0.13541694, 0.46388632],
       [0.52501604, 0.99574051],
       [0.62047015, 0.73469439]])]


# 9.  Date type using Numpy

Numpy implements dates through the np.datetime64 object which supports a precision till nanoseconds. You can create one using a standard YYYY-MM-DD formatted date strings.

In [ ]:
date64 = np.datetime64('2018-02-04 23:10:10')
date64

numpy.datetime64('2018-02-04T23:10:10')

In [ ]:
dt64 = np.datetime64(date64, 'D')
dt64

numpy.datetime64('2018-02-04')

In [ ]:
tenminutes = np.timedelta64(10, 'm')  # 10 minutes
tenseconds = np.timedelta64(10, 's')  # 10 seconds
tennanoseconds = np.timedelta64(10, 'ns')  # 10 nanoseconds

print('Add 10 days: ', dt64 + 10)
print('Add 10 minutes: ', dt64 + tenminutes)
print('Add 10 seconds: ', dt64 + tenseconds)
print('Add 10 nanoseconds: ', dt64 + tennanoseconds)

Add 10 days:  2018-02-14
Add 10 minutes:  2018-02-04T00:10
Add 10 seconds:  2018-02-04T00:00:10
Add 10 nanoseconds:  2018-02-04T00:00:00.000000010


#### How to create a sequence of dates?

In [ ]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-10'))
print(dates)

['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09']


#### How to convert numpy.datetime64 to datetime.datetime object?

In [ ]:
import datetime
dt = dt64.tolist()
dt

datetime.date(2018, 2, 4)

In [ ]:
print('Year: ', dt.year)  
print('Day of month: ', dt.day)
print('Month of year: ', dt.month)  
print('Day of Week: ', dt.weekday())  # Sunday

Year:  2018
Day of month:  4
Month of year:  2
Day of Week:  6
