## Exercise 1

İstənilən ölçüdə array yaradın. Array-in ətrafındakı elementləri 1-lərdən, daxilindəkilər isə 0-lardan ibarət olmalıdır.

Məsələn:

1)

    [[1,1,1,1,1],
     [1,0,0,0,1],
     [1,0,0,0,1],
     [1,1,1,1,1]]
     
2)

    [[1,1,1],
     [1,0,1],
     [1,1,1]]
     
3)

    [[1,1,1,1],
     [1,0,0,1],
     [1,1,1,1]]     

In [49]:
import numpy as np

arr1=np.ones((4,5),dtype=int)
print(arr1) 
for i in range(arr1.shape[0]):
    if i!=0 and i!=arr1.shape[0]-1:
        arr1[i][1:len(arr1[i])-1]=0
print(arr1)


        




[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Exercise 2
Verilmiş 1 ölçülü massivin [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14] hər 3-cü elementi ilə başlayan 6 sətir və 4 sütundan ibarət yeni massiv yaradın

In [120]:
array_1=np.arange(14)



## Exercise 3
Random ədədlərdən ibarət 2 ölçülü massiv yaradın. Yaratdığınız massivin hər sətrini tərsinə çevirməklə yeni massiv yaradın.

Məsələn:
 
     [[1,2,3,4,5],
      [6,7,8,9,10],
      [10,11,12,13,14]]
 
Gözlənilən cavab:
 
     [[5,4,3,2,1],
      [10,9,8,7,6],
      [14,13,12,11,10]]

In [79]:
arr3=np.random.randint(20,size=(3,5))
print(arr3)
for i in range(arr3.shape[0]):
    arr3[i]=arr3[i][::-1]
print(arr3)


[[11  0 13  4  3]
 [17  7  1 10  1]
 [18  4 16 18 11]]
[[ 3  4 13  0 11]
 [ 1 10  1  7 17]
 [11 18 16  4 18]]


## Exercise 4
Random ədədlərdən ibarət 2 ölçülü massiv yaradın. Yaratdığınız massivin sətirləri ilə sütunlarının yerini dəyişməklə yeni massiv yaradın.

Məsələn:

    [[1,2,3,4,5],
     [6,7,8,9,10],
     [10,11,12,13,14]]

Gözlənilən cavab:

    [[1,6,10],
     [2,7,11],
     [3,8,12],
     [4,9,13],
     [5,10,14]]


​

In [83]:
arr3=np.random.randint(20,size=(3,5))
print(arr3)
arr3=arr3.T
print(arr3)


[[ 7  5  7  7 15]
 [10 10  5  4  9]
 [15 12 16 11  6]]
[[ 7 10 15]
 [ 5 10 12]
 [ 7  5 16]
 [ 7  4 11]
 [15  9  6]]


## Exercise 5

Verilmiş 2 ölçülü massivdən diagonalı bu massivin sətirlərindən ibarət olan yeni massiv yaradın.

Gözlənilən cavab:

       [[[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]],

       [[4, 0, 0],
        [0, 5, 0],
        [0, 0, 6]],

       [[7, 0, 0],
        [0, 8, 0],
        [0, 0, 9]]]

In [113]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
for i in range(arr.shape[0]):
    a=np.diag(arr[i])
    print(f"{a}\n")  





[[1 0 0]
 [0 2 0]
 [0 0 3]]

[[4 0 0]
 [0 5 0]
 [0 0 6]]

[[7 0 0]
 [0 8 0]
 [0 0 9]]

