## Tapşırıq 1

(5,5) ölçülü müsbət tam ədədlərdən ibarət array-in polindrom olan sətir və ya sütunlarını göstərin. Polindrom ədəd dedikdə məsələn: 323, 6336, 54245, 623326 nəzərdə tutulur.

In [8]:
import numpy as np

array = np.array([[1,0,7,0,1],
                [2,120,4,1,10],
                [1,3,0,3,1],
                [1,120,31,1,19],
                [11,0,7,0,11]])

array
print(array.shape)

def polyndrome(array):
    #polyndrome row
    for row in array:
        if list(row) == list(row)[::-1]:
            print('Polyndrome row:',row)
            
            
    #polyndrome column
    for i in range(array.shape[0]):
        col = array[:, i]
        if list(col) == list(col[::-1]):
            print('Polyndrome column:',col)
    return

polyndrome(array)

(5, 5)
Polyndrome row: [1 0 7 0 1]
Polyndrome row: [1 3 0 3 1]
Polyndrome row: [11  0  7  0 11]
Polyndrome column: [  0 120   3 120   0]
Polyndrome column: [0 1 3 1 0]


## Tapşırıq 2

İstənilən 2-ölçülü array-in hər sətiri üçün ən böyük ədədlə ən kiçik ədədin nisbətini tapın

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[5.0, 1.6666666666666667, 1.3636363636363635, 1.25]


## Tapşırıq 3

Verilmiş 2-ölçülü array-in hər elementinin əvəzinə onun rankını yazaraq yeni bir array yaradın

Gözlənilən cavab:

[[4 2 6 0 8]

[7 9 3 5 1]]

In [18]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])

print(a)

# your code
print(a.ravel().argsort())
a.ravel().argsort().argsort().reshape(a.shape)

# 0 0 4 8 9 9 15 16 17 17
# 0 1 2 3 4 5 6  7  8  9

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[3 9 1 7 0 8 2 5 4 6]


### Tapşırıq 4

Verilən bir ölçülü array-dən one hot encoding prinsipi ilə yeni bir array yaradın  

In [4]:
np.where(arr == arr[0])

(array([0, 0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))

In [5]:
arr = np.array([2, 3, 2, 2, 2, 1])
# your code

rowsize = arr.shape[0]
uniques = np.unique(arr)
colsize = len(uniques)
new_arr = np.full((rowsize, colsize), 0)

print('  ',uniques)
for i, el in enumerate(arr):
    pos = np.where(uniques == el)
    new_arr[i,pos] = 1
    
print(np.c_[arr[:, None], new_arr])

   [1 2 3]
[[2 0 1 0]
 [3 0 0 1]
 [2 0 1 0]
 [2 0 1 0]
 [2 0 1 0]
 [1 1 0 0]]


## Tapşırıq 5

Verilmiş array-in top 5 elementini və onların pozisiyalarını əldə edin

In [6]:
np.random.seed(100)
a = np.random.randint(1,50, 20).reshape(4,5)
print(a)

a = a.ravel()
b = np.sort(np.unique(a))[-5:]
# your code


for i in b:
    print('Element:', i, 'On position:', np.where(a==i)[0])
    print('\n')

[[ 9 25  4 40 24]
 [16 49 11 31 35]
 [ 3 35 15 35 49]
 [25 16 37 44 17]]
Element: 35 On position: [ 9 11 13]


Element: 37 On position: [17]


Element: 40 On position: [3]


Element: 44 On position: [18]


Element: 49 On position: [ 6 14]


